---
applications:
- name: hud-disaster-data-staging
  path: ../../templates/dist
  memory: 64M
  host: hud-disaster-data-staging
  buildpack: https://github.com/cloudfoundry/nodejs-buildpack
  env:
    FORCE_HTTPS: true
