---
applications:
- name: hud-disaster-data-staging
  path: ../../app
  memory: 128M
  host: hud-disaster-data-staging
  buildpack: https://github.com/cloudfoundry/nodejs-buildpack
  env:
    FORCE_HTTPS: true
